// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthPayload struct {
	Token  string `json:"token"`
	UserID string `json:"userId"`
	Role   string `json:"role"`
}

type Contestant struct {
	ID             string          `json:"id"`
	UserID         string          `json:"userId"`
	Sbd            *string         `json:"sbd,omitempty"`
	Status         string          `json:"status"`
	IsPublic       bool            `json:"isPublic"`
	PersonalInfo   *PersonalInfo   `json:"personalInfo"`
	PhysicalInfo   *PhysicalInfo   `json:"physicalInfo,omitempty"`
	SkillEducation *SkillEducation `json:"skillEducation,omitempty"`
	Portfolio      *Portfolio      `json:"portfolio,omitempty"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
}

type CreateContestantInput struct {
	FullName       string   `json:"fullName"`
	Dob            string   `json:"dob"`
	Nationality    string   `json:"nationality"`
	IdentityCard   *string  `json:"identityCard,omitempty"`
	Phone          string   `json:"phone"`
	Email          string   `json:"email"`
	Address        string   `json:"address"`
	Job            string   `json:"job"`
	Height         float64  `json:"height"`
	Weight         float64  `json:"weight"`
	Measurements   string   `json:"measurements"`
	EducationLevel *string  `json:"educationLevel,omitempty"`
	Languages      []string `json:"languages,omitempty"`
	Skills         []string `json:"skills,omitempty"`
	AvatarURL      *string  `json:"avatarUrl,omitempty"`
	GalleryUrls    []string `json:"galleryUrls,omitempty"`
	Introduction   *string  `json:"introduction,omitempty"`
	SocialLinks    []string `json:"socialLinks,omitempty"`
}

type CreateFeedbackInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Type    string `json:"type"`
}

type Feedback struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Type      string    `json:"type"`
	Status    string    `json:"status"`
	Reply     *string   `json:"reply,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type Mutation struct {
}

type PersonalInfo struct {
	FullName     string    `json:"fullName"`
	Dob          time.Time `json:"dob"`
	Nationality  *string   `json:"nationality,omitempty"`
	Gender       *string   `json:"gender,omitempty"`
	IdentityCard *string   `json:"identityCard,omitempty"`
	Phone        *string   `json:"phone,omitempty"`
	Email        *string   `json:"email,omitempty"`
	Address      *string   `json:"address,omitempty"`
	Job          *string   `json:"job,omitempty"`
}

type PhysicalInfo struct {
	Height       float64 `json:"height"`
	Weight       float64 `json:"weight"`
	Measurements *string `json:"measurements,omitempty"`
}

type Portfolio struct {
	AvatarURL    *string  `json:"avatarUrl,omitempty"`
	GalleryUrls  []string `json:"galleryUrls,omitempty"`
	VideoURL     *string  `json:"videoUrl,omitempty"`
	Introduction *string  `json:"introduction,omitempty"`
	SocialLinks  []string `json:"socialLinks,omitempty"`
}

type Query struct {
}

type Schedule struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description,omitempty"`
	StartTime   time.Time `json:"startTime"`
	EndTime     time.Time `json:"endTime"`
	Location    string    `json:"location"`
	Type        string    `json:"type"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Score struct {
	ID             string         `json:"id"`
	RoundID        string         `json:"roundId"`
	Sbd            string         `json:"sbd"`
	TotalScore     float64        `json:"totalScore"`
	CriteriaScores map[string]any `json:"criteriaScores,omitempty"`
	Comment        *string        `json:"comment,omitempty"`
	CreatedAt      time.Time      `json:"createdAt"`
}

type SkillEducation struct {
	EducationLevel *string  `json:"educationLevel,omitempty"`
	Languages      []string `json:"languages,omitempty"`
	Skills         []string `json:"skills,omitempty"`
}

type UpdateContestantInput struct {
	FullName       *string  `json:"fullName,omitempty"`
	Dob            *string  `json:"dob,omitempty"`
	Nationality    *string  `json:"nationality,omitempty"`
	Job            *string  `json:"job,omitempty"`
	Phone          *string  `json:"phone,omitempty"`
	Email          *string  `json:"email,omitempty"`
	Address        *string  `json:"address,omitempty"`
	Height         *float64 `json:"height,omitempty"`
	Weight         *float64 `json:"weight,omitempty"`
	Measurements   *string  `json:"measurements,omitempty"`
	EducationLevel *string  `json:"educationLevel,omitempty"`
	Languages      []string `json:"languages,omitempty"`
	Skills         []string `json:"skills,omitempty"`
	AvatarURL      *string  `json:"avatarUrl,omitempty"`
	GalleryUrls    []string `json:"galleryUrls,omitempty"`
	Introduction   *string  `json:"introduction,omitempty"`
	SocialLinks    []string `json:"socialLinks,omitempty"`
}
