package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

/*
 Tác dụng của auth.resolvers.go:
 - Nhận GraphQL Mutation Login/Register.
 - Tích hợp Rate Limiting (r.checkRateLimit) để chống Brute-force dò mật khẩu.
*/

import (
	"context"
	gqlmodel "cuoc_thi_hoa_hau/graph/model"
	"cuoc_thi_hoa_hau/internal/model"
	"errors"
	"log/slog"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*gqlmodel.AuthPayload, error) {
	if err := r.checkRateLimit(ctx, "login", email); err != nil {
		slog.Warn("Rate limit exceeded", "action", "login", "email", email)
		return nil, err
	}

	if err := validateAuthInput(email, password); err != nil {
		return nil, err
	}

	claims, token, err := r.AuthSvc.Login(ctx, email, password)
	if err != nil {
		slog.Warn("Failed login attempt", "email", email, "error", err.Error())
		return nil, errors.New("invalid credentials")
	}

	return &gqlmodel.AuthPayload{
		Token:  token,
		UserID: claims.UserID,
		Role:   claims.Role,
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*gqlmodel.AuthPayload, error) {
	if err := validateAuthInput(email, password); err != nil {
		return nil, err
	}

	claims, token, err := r.AuthSvc.Register(ctx, email, password, string(model.RoleCandidate))
	if err != nil {
		return nil, err
	}

	return &gqlmodel.AuthPayload{
		Token:  token,
		UserID: claims.UserID,
		Role:   claims.Role,
	}, nil
}
