package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

/*
 Tác dụng của contestant.resolvers.go:
 - Đây là Resolver phức tạp nhất do chứa nhiều Queries/Mutations liên quan tới Thí Sinh (Contestant).
 - Nó gọi vào validation package trước tiên.
 - Sau đó Map Input sang Domain Entity -> Đẩy xuống Service xử lý -> Nhận kết quả -> Map ngược lại Graph Object.
 - Kết hợp Caching cực kỳ mạnh mẽ cho các API công khai (Public) để chịu tải cao.
*/

import (
	"context"
	"cuoc_thi_hoa_hau/graph/middleware"
	gqlmodel "cuoc_thi_hoa_hau/graph/model"
	"cuoc_thi_hoa_hau/internal/handler/validation"
	"cuoc_thi_hoa_hau/internal/model"
	"errors"
	"fmt"
	"log"
	"time"
)

// CreateContestantProfile is the resolver for the createContestantProfile field.
func (r *mutationResolver) CreateContestantProfile(ctx context.Context, input gqlmodel.CreateContestantInput) (*gqlmodel.Contestant, error) {
	if err := validation.ValidateCreateContestantInput(input); err != nil {
		return nil, fmt.Errorf("validation error: %w", err)
	}

	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	dob, err := time.Parse(model.DateLayoutISO, input.Dob)
	if err != nil {
		return nil, errors.New("invalid date format (YYYY-MM-DD)")
	}

	domainEntity := ToDomainContestant(input, dob)

	created, err := r.ContestantSvc.CreateProfile(ctx, userID, domainEntity)
	if err != nil {
		return nil, err
	}

	return mapContestantToGraphOwner(created), nil
}

// UpdateContestantProfile is the resolver for the updateContestantProfile field.
func (r *mutationResolver) UpdateContestantProfile(ctx context.Context, input gqlmodel.UpdateContestantInput) (*gqlmodel.Contestant, error) {
	if err := validation.ValidateUpdateContestantInput(input); err != nil {
		return nil, fmt.Errorf("validation error: %w", err)
	}

	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	domainEntity, err := ToDomainUpdateContestant(input)
	if err != nil {
		return nil, fmt.Errorf("invalid mapping: %w", err)
	}

	updated, err := r.ContestantSvc.UpdateProfile(ctx, userID, domainEntity)
	if err != nil {
		return nil, err
	}

	return mapContestantToGraphOwner(updated), nil
}

// ApproveContestant is the resolver for the approveContestant field.
func (r *mutationResolver) ApproveContestant(ctx context.Context, id string, isApproved bool) (*gqlmodel.Contestant, error) {
	if err := middleware.RequirePermission(ctx, model.PermContestantWrite); err != nil {
		return nil, err
	}
	sub := middleware.ForContext(ctx)

	updated, err := r.ContestantSvc.ApproveContestant(ctx, sub, id, isApproved)
	if err != nil {
		return nil, err
	}

	return mapContestantToGraphFull(updated), nil
}

// VoteForContestant is the resolver for the voteForContestant field.
func (r *mutationResolver) VoteForContestant(ctx context.Context, id string) (bool, error) {
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return false, errors.New("unauthorized")
	}

	if err := r.checkVoteRateLimit(ctx, userID, id); err != nil {
		return false, err
	}

	ip, ua := middleware.GetClientInfo(ctx)

	if err := r.ContestantSvc.VoteForContestant(ctx, userID, id, ip, ua); err != nil {
		return false, err
	}

	return true, nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*gqlmodel.Contestant, error) {
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	profile, err := r.ContestantSvc.GetMyProfile(ctx, userID)
	if err != nil {
		return nil, err
	}
	return mapContestantToGraphOwner(profile), nil
}

// PublicContestants lấy danh sách public.
// Do API này ai cũng có thể gọi (Anonymous), cực kì dễ bị spam làm sập Database.
// -> BẮT BUỘC áp dụng Caching (Redis) ở đây dựa trên số Trang (Page) và Số lượng (Limit).
func (r *queryResolver) PublicContestants(ctx context.Context, page *int, limit *int) ([]*gqlmodel.Contestant, error) {
	p, l := validation.NormalizePagination(page, limit)
	offset := int64((p - 1) * l)
	limit64 := int64(l)

	cacheKey := fmt.Sprintf("public_contestants:p%d:l%d", p, l)
	var cachedRes []*gqlmodel.Contestant
	if err := r.CacheSvc.Get(ctx, cacheKey, &cachedRes); err == nil && cachedRes != nil {
		return cachedRes, nil
	}

	list, _, err := r.ContestantSvc.GetPublicList(ctx, limit64, offset)
	if err != nil {
		return nil, err
	}

	var res []*gqlmodel.Contestant
	for _, c := range list {
		res = append(res, mapPublicContestantToGraph(c))
	}

	if err := r.CacheSvc.Set(ctx, cacheKey, res, 5*time.Minute); err != nil {
		log.Printf("[Cache] Failed to set public contestants: %v", err)
	}

	return res, nil
}

// PublicContestantDetail is the resolver for the publicContestantDetail field.
func (r *queryResolver) PublicContestantDetail(ctx context.Context, id string) (*gqlmodel.Contestant, error) {
	cacheKey := fmt.Sprintf("contestant_detail:%s", id)
	var cached *gqlmodel.Contestant
	if err := r.CacheSvc.Get(ctx, cacheKey, &cached); err == nil && cached != nil {
		return cached, nil
	}

	c, err := r.ContestantSvc.GetPublicDetail(ctx, id)
	if err != nil {
		return nil, err
	}
	res := mapPublicContestantToGraph(c)

	_ = r.CacheSvc.Set(ctx, cacheKey, res, 5*time.Minute)

	return res, nil
}

// AdminContestants is the resolver for the adminContestants field.
func (r *queryResolver) AdminContestants(ctx context.Context, page *int, limit *int, status *string) ([]*gqlmodel.Contestant, error) {
	if err := middleware.RequirePermission(ctx, model.PermContestantWrite); err != nil {
		return nil, err
	}

	p, l := validation.NormalizePagination(page, limit)

	list, _, err := r.ContestantSvc.GetAdminList(ctx, int64(l), int64((p-1)*l), status)
	if err != nil {
		return nil, err
	}

	var res []*gqlmodel.Contestant
	for _, c := range list {
		res = append(res, mapContestantToGraphFull(c))
	}
	return res, nil
}
