package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

/*
 Tác dụng của feedback.resolvers.go:
 - Map Mutation SendFeedback xuống Service.
 - Lọc UserID từ Context (đã được middleware parse) để gán cho người dùng hiện tại mà không cần họ tự truyền mã.
*/

import (
	"context"
	"cuoc_thi_hoa_hau/graph/middleware"
	gqlmodel "cuoc_thi_hoa_hau/graph/model"
	"cuoc_thi_hoa_hau/internal/model"
	"errors"
)

// SendFeedback allows a candidate to submit a feedback.
func (r *mutationResolver) SendFeedback(ctx context.Context, input gqlmodel.CreateFeedbackInput) (bool, error) {
	user, ok := ctx.Value(middleware.UserCtxKey).(*model.AuthClaims)
	if !ok || user.Role != string(model.RoleCandidate) {
		return false, errors.New("bạn không có quyền thực hiện hành động này")
	}

	feedback := &model.Feedback{
		Title:   input.Title,
		Content: input.Content,
		Type:    model.FeedbackType(input.Type),
	}

	if err := r.FeedbackSvc.SendFeedback(ctx, user.UserID, feedback); err != nil {
		return false, err
	}

	return true, nil
}

// MyFeedbacks retrieves feedbacks submitted by the requesting user.
func (r *queryResolver) MyFeedbacks(ctx context.Context) ([]*gqlmodel.Feedback, error) {
	user, ok := ctx.Value(middleware.UserCtxKey).(*model.AuthClaims)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	l := int64(10)
	o := int64(0)

	list, _, err := r.FeedbackSvc.GetMyFeedbacks(ctx, user.UserID, l, o)
	if err != nil {
		return nil, err
	}

	items := make([]*gqlmodel.Feedback, 0)
	for _, f := range list {
		items = append(items, &gqlmodel.Feedback{
			ID:        f.ID,
			Title:     f.Title,
			Content:   f.Content,
			Type:      string(f.Type),
			Status:    string(f.Status),
			CreatedAt: f.CreatedAt,
		})
	}

	return items, nil
}
