package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

/*
 Tác dụng của schedule.resolvers.go:
 - Wrapper gọi xuống ScheduleSvc để lấy lịch trình.
*/

import (
	"context"
	gqlmodel "cuoc_thi_hoa_hau/graph/model"
	"fmt"
)

// Schedules is the resolver for the schedules field.
func (r *queryResolver) Schedules(ctx context.Context, filterType *string) ([]*gqlmodel.Schedule, error) {
	panic(fmt.Errorf("not implemented: Schedules - schedules"))
}

// ScheduleDetail is the resolver for the scheduleDetail field.
func (r *queryResolver) ScheduleDetail(ctx context.Context, id string) (*gqlmodel.Schedule, error) {
	panic(fmt.Errorf("not implemented: ScheduleDetail - scheduleDetail"))
}
