package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

/*
 Package resolver xử lý các endpoints.
 Tác dụng của schema.resolvers.go:
 - Đây là file sinh tự động nhưng hàm Ping/Health là chỗ ta tự viết để monitor server có sống hay không.
 - Hay dùng cho livenessProbe trong Kubernetes.
*/

import (
	"context"
	"cuoc_thi_hoa_hau/graph/generated"
	"fmt"
)

// Ping is the resolver for the ping field.
func (r *mutationResolver) Ping(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Ping - ping"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
