package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

/*
 Tác dụng của score.resolvers.go:
 - Middleware.RequirePermission được gọi trực tiếp ở đây chặn ngay tại Controller nếu không có cờ model.PermScoreWrite.
 - Lấy IP + UA từ Context truyền xuống Service để phục vụ Audit (Kiểm toán chống gian lận).
*/

import (
	"context"
	"cuoc_thi_hoa_hau/graph/middleware"
	gqlmodel "cuoc_thi_hoa_hau/graph/model"
	"cuoc_thi_hoa_hau/internal/model"
	"errors"
)

// SubmitScore is the resolver for the submitScore field.
func (r *mutationResolver) SubmitScore(ctx context.Context, input gqlmodel.ScoreInput) (*gqlmodel.Score, error) {
	if err := middleware.RequirePermission(ctx, model.PermScoreWrite); err != nil {
		return nil, err
	}

	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	score := ToDomainScore(input)

	ip, ua := middleware.GetClientInfo(ctx)

	if err := r.ScoreSvc.SubmitScore(ctx, userID, score, ip, ua); err != nil {
		return nil, err
	}

	return ToGraphScore(score), nil
}

// MyScores is the resolver for the myScores field.
func (r *queryResolver) MyScores(ctx context.Context) ([]*gqlmodel.Score, error) {
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized: vui lòng đăng nhập")
	}

	scores, err := r.ScoreSvc.GetMyScores(ctx, userID)
	if err != nil {
		return nil, err
	}

	var result []*gqlmodel.Score
	for _, s := range scores {
		result = append(result, ToGraphScore(s))
	}

	return result, nil
}
