/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContestantRouteImport } from './routes/contestant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContestantIndexRouteImport } from './routes/contestant/index'
import { Route as ContestantRegisterRouteImport } from './routes/contestant/register'
import { Route as ContestantDashboardRouteImport } from './routes/contestant/dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantRoute = ContestantRouteImport.update({
  id: '/contestant',
  path: '/contestant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantIndexRoute = ContestantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContestantRoute,
} as any)
const ContestantRegisterRoute = ContestantRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ContestantRoute,
} as any)
const ContestantDashboardRoute = ContestantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ContestantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contestant': typeof ContestantRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/contestant/dashboard': typeof ContestantDashboardRoute
  '/contestant/register': typeof ContestantRegisterRoute
  '/contestant/': typeof ContestantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/contestant/dashboard': typeof ContestantDashboardRoute
  '/contestant/register': typeof ContestantRegisterRoute
  '/contestant': typeof ContestantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contestant': typeof ContestantRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/contestant/dashboard': typeof ContestantDashboardRoute
  '/contestant/register': typeof ContestantRegisterRoute
  '/contestant/': typeof ContestantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contestant'
    | '/login'
    | '/register'
    | '/contestant/dashboard'
    | '/contestant/register'
    | '/contestant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/contestant/dashboard'
    | '/contestant/register'
    | '/contestant'
  id:
    | '__root__'
    | '/'
    | '/contestant'
    | '/login'
    | '/register'
    | '/contestant/dashboard'
    | '/contestant/register'
    | '/contestant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContestantRoute: typeof ContestantRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestant': {
      id: '/contestant'
      path: '/contestant'
      fullPath: '/contestant'
      preLoaderRoute: typeof ContestantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestant/': {
      id: '/contestant/'
      path: '/'
      fullPath: '/contestant/'
      preLoaderRoute: typeof ContestantIndexRouteImport
      parentRoute: typeof ContestantRoute
    }
    '/contestant/register': {
      id: '/contestant/register'
      path: '/register'
      fullPath: '/contestant/register'
      preLoaderRoute: typeof ContestantRegisterRouteImport
      parentRoute: typeof ContestantRoute
    }
    '/contestant/dashboard': {
      id: '/contestant/dashboard'
      path: '/dashboard'
      fullPath: '/contestant/dashboard'
      preLoaderRoute: typeof ContestantDashboardRouteImport
      parentRoute: typeof ContestantRoute
    }
  }
}

interface ContestantRouteChildren {
  ContestantDashboardRoute: typeof ContestantDashboardRoute
  ContestantRegisterRoute: typeof ContestantRegisterRoute
  ContestantIndexRoute: typeof ContestantIndexRoute
}

const ContestantRouteChildren: ContestantRouteChildren = {
  ContestantDashboardRoute: ContestantDashboardRoute,
  ContestantRegisterRoute: ContestantRegisterRoute,
  ContestantIndexRoute: ContestantIndexRoute,
}

const ContestantRouteWithChildren = ContestantRoute._addFileChildren(
  ContestantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContestantRoute: ContestantRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
