package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"cuoc_thi_hoa_hau/internal/adapter/graph/model"
	"cuoc_thi_hoa_hau/internal/core/domain"
	"errors"
	"fmt"
	"log/slog"
	"time"
	"unicode"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	// 1. Rate Limiting
	if err := r.checkRateLimit(ctx, "login", email); err != nil {
		slog.Warn("Rate limit exceeded", "action", "login", "email", email)
		return nil, err
	}

	// 2. Validate
	if err := validateAuthInput(email, password); err != nil {
		return nil, err
	}

	// 3. Call Service
	claims, token, err := r.AuthSvc.Login(ctx, email, password)
	if err != nil {
		slog.Warn("Failed login attempt", "email", email, "error", err.Error())
		return nil, errors.New("invalid credentials")
	}

	return &model.AuthPayload{
		Token:  token,
		UserID: claims.UserID,
		Role:   claims.Role,
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	// 1. Validate
	if err := validateAuthInput(email, password); err != nil {
		return nil, err
	}

	// 2. Call Service
	claims, token, err := r.AuthSvc.Register(ctx, email, password, string(domain.RoleCandidate))
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token:  token,
		UserID: claims.UserID,
		Role:   claims.Role,
	}, nil
}

// Helper function to validate authentication input
func validateAuthInput(email, password string) error {
	if len(email) < 3 {
		return errors.New("email must be at least 3 characters")
	}

	if len(password) < 8 {
		return errors.New("password must be at least 8 characters")
	}

	var (
		hasUpper   bool
		hasLower   bool
		hasNumber  bool
		hasSpecial bool
	)

	for _, char := range password {
		switch {
		case unicode.IsUpper(char):
			hasUpper = true
		case unicode.IsLower(char):
			hasLower = true
		case unicode.IsNumber(char):
			hasNumber = true
		case unicode.IsPunct(char) || unicode.IsSymbol(char):
			hasSpecial = true
		}
	}

	if !hasUpper || !hasLower || !hasNumber || !hasSpecial {
		return errors.New("password must contain at least one uppercase, lowercase, number, and special character")
	}

	return nil
}

// Helper method to check rate limiting for authentication operations
func (r *mutationResolver) checkRateLimit(ctx context.Context, action, key string) error {
	if r.CacheSvc == nil {
		return nil // skip if cache not available (dev mode)
	}

	limitKey := fmt.Sprintf("rate_limit:%s:%s", action, key)
	count, err := r.CacheSvc.Incr(ctx, limitKey)
	if err != nil {
		slog.Error("Rate limit counter failed", "error", err, "key", limitKey)
		return nil
	}

	if count == 1 {
		// Set expiry on first increment
		r.CacheSvc.Set(ctx, limitKey, 1, 1*time.Minute)
	}

	if count > 5 {
		return errors.New("too many attempts, please try again later")
	}
	return nil
}
