package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"cuoc_thi_hoa_hau/internal/adapter/graph/middleware"
	"cuoc_thi_hoa_hau/internal/adapter/graph/model"
	"cuoc_thi_hoa_hau/internal/core/domain"
	"cuoc_thi_hoa_hau/internal/pkg/common"
	"errors"
	"time"
)

// CreateContestantProfile is the resolver for the createContestantProfile field.
func (r *mutationResolver) CreateContestantProfile(ctx context.Context, input model.CreateContestantInput) (*model.Contestant, error) {
	// 1. Map Graph Input to Domain Entity
	dob, err := time.Parse(common.DateLayoutISO, input.Dob)
	if err != nil {
		return nil, errors.New("invalid date format (XYYYY-MM-DD)")
	}

	// Handle Optional IdentityCard
	idCard := ""
	if input.IdentityCard != nil {
		idCard = *input.IdentityCard
	}

	domainEntity := &domain.Contestant{
		PersonalInfo: domain.PersonalInfo{
			FullName:     input.FullName,
			DateOfBirth:  dob,
			Nationality:  input.Nationality,
			IdentityCard: idCard,
			Phone:        input.Phone,
			Email:        input.Email,
			Address:      input.Address,
			Job:          input.Job,
		},
		PhysicalInfo: domain.PhysicalInfo{
			Height:       input.Height,
			Weight:       input.Weight,
			Measurements: input.Measurements,
		},
		SkillEdu: domain.SkillEducation{
			Languages: input.Languages,
			Skills:    input.Skills,
		},
		Portfolio: domain.Portfolio{
			GalleryURLs: input.GalleryUrls,
			SocialLinks: input.SocialLinks,
		},
	}

	if input.EducationLevel != nil {
		domainEntity.SkillEdu.EducationLevel = *input.EducationLevel
	}
	if input.Languages != nil {
		domainEntity.SkillEdu.Languages = input.Languages
	}
	if input.Skills != nil {
		domainEntity.SkillEdu.Skills = input.Skills
	}

	if input.AvatarURL != nil {
		domainEntity.Portfolio.AvatarURL = *input.AvatarURL
	}
	if input.GalleryUrls != nil {
		domainEntity.Portfolio.GalleryURLs = input.GalleryUrls
	}
	if input.Introduction != nil {
		domainEntity.Portfolio.Introduction = *input.Introduction
	}
	if input.SocialLinks != nil {
		domainEntity.Portfolio.SocialLinks = input.SocialLinks
	}

	// 2. Call Service
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	created, err := r.ContestantSvc.CreateProfile(ctx, userID, domainEntity)
	if err != nil {
		return nil, err
	}

	// 3. Map Domain Entity back to Graph Model
	return mapContestantToGraph(created), nil
}

// UpdateContestantProfile is the resolver for the updateContestantProfile field.
func (r *mutationResolver) UpdateContestantProfile(ctx context.Context, input model.UpdateContestantInput) (*model.Contestant, error) {
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	// 1. Map Input to Domain Entity (Partial)
	domainEntity := &domain.Contestant{}

	if input.FullName != nil {
		domainEntity.PersonalInfo.FullName = *input.FullName
	}
	if input.Dob != nil {
		dob, err := time.Parse(common.DateLayoutISO, *input.Dob)
		if err != nil {
			return nil, errors.New("invalid date format (YYYY-MM-DD)")
		}
		domainEntity.PersonalInfo.DateOfBirth = dob
	}
	if input.Nationality != nil {
		domainEntity.PersonalInfo.Nationality = *input.Nationality
	}
	if input.Job != nil {
		domainEntity.PersonalInfo.Job = *input.Job
	}
	if input.Phone != nil {
		domainEntity.PersonalInfo.Phone = *input.Phone
	}
	if input.Email != nil {
		domainEntity.PersonalInfo.Email = *input.Email
	}
	if input.Address != nil {
		domainEntity.PersonalInfo.Address = *input.Address
	}

	if input.Height != nil {
		domainEntity.PhysicalInfo.Height = *input.Height
	}
	if input.Weight != nil {
		domainEntity.PhysicalInfo.Weight = *input.Weight
	}
	if input.Measurements != nil {
		domainEntity.PhysicalInfo.Measurements = *input.Measurements
	}

	if input.EducationLevel != nil {
		domainEntity.SkillEdu.EducationLevel = *input.EducationLevel
	}
	if input.Languages != nil {
		domainEntity.SkillEdu.Languages = input.Languages
	}
	if input.Skills != nil {
		domainEntity.SkillEdu.Skills = input.Skills
	}

	if input.AvatarURL != nil {
		domainEntity.Portfolio.AvatarURL = *input.AvatarURL
	}
	if input.GalleryUrls != nil {
		domainEntity.Portfolio.GalleryURLs = input.GalleryUrls
	}
	if input.Introduction != nil {
		domainEntity.Portfolio.Introduction = *input.Introduction
	}
	if input.SocialLinks != nil {
		domainEntity.Portfolio.SocialLinks = input.SocialLinks
	}

	// 2. Call Service
	updated, err := r.ContestantSvc.UpdateProfile(ctx, userID, domainEntity)
	if err != nil {
		return nil, err
	}

	// 3. Map result back
	return mapContestantToGraph(updated), nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.Contestant, error) {
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	profile, err := r.ContestantSvc.GetMyProfile(ctx, userID)
	if err != nil {
		return nil, err
	}
	return mapContestantToGraph(profile), nil
}

// PublicContestants is the resolver for the publicContestants field.
func (r *queryResolver) PublicContestants(ctx context.Context, page *int, limit *int) ([]*model.Contestant, error) {
	p, l := 1, 20
	if page != nil {
		p = *page
	}
	if limit != nil {
		l = *limit
	}

	list, _, err := r.ContestantSvc.GetPublicList(ctx, int64(p), int64(l))
	if err != nil {
		return nil, err
	}

	var res []*model.Contestant
	for _, c := range list {
		res = append(res, mapContestantToGraph(c))
	}
	return res, nil
}

// PublicContestantDetail is the resolver for the publicContestantDetail field.
func (r *queryResolver) PublicContestantDetail(ctx context.Context, id string) (*model.Contestant, error) {
	// TODO: Implement GetByID in Service
	return nil, nil
}

// Helpers
func mapContestantToGraph(d *domain.Contestant) *model.Contestant {
	if d == nil {
		return nil
	}
	return &model.Contestant{
		ID:       d.ID,
		UserID:   d.UserID,
		Sbd:      &d.SBD,
		Status:   string(d.Status),
		IsPublic: d.IsPublic,
		PersonalInfo: &model.PersonalInfo{
			FullName:     d.PersonalInfo.FullName,
			Dob:          d.PersonalInfo.DateOfBirth,
			Nationality:  &d.PersonalInfo.Nationality,
			Gender:       &d.PersonalInfo.Gender,
			IdentityCard: &d.PersonalInfo.IdentityCard,
			Phone:        &d.PersonalInfo.Phone,
			Email:        &d.PersonalInfo.Email,
			Address:      &d.PersonalInfo.Address,
			Job:          &d.PersonalInfo.Job,
		},
		PhysicalInfo: &model.PhysicalInfo{
			Height:       d.PhysicalInfo.Height,
			Weight:       d.PhysicalInfo.Weight,
			Measurements: &d.PhysicalInfo.Measurements,
		},
		Portfolio: &model.Portfolio{
			AvatarURL:    &d.Portfolio.AvatarURL,
			GalleryUrls:  d.Portfolio.GalleryURLs,
			VideoURL:     &d.Portfolio.VideoURL,
			Introduction: &d.Portfolio.Introduction,
			SocialLinks:  d.Portfolio.SocialLinks,
		},
		CreatedAt: d.CreatedAt,
		UpdatedAt: d.UpdatedAt,
	}
}

func convertStringPtrSlice(in []string) []*string {
	var out []*string
	for _, s := range in {
		str := s
		out = append(out, &str)
	}
	return out
}
