package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"cuoc_thi_hoa_hau/internal/adapter/graph/middleware"
	"cuoc_thi_hoa_hau/internal/adapter/graph/model"
	"cuoc_thi_hoa_hau/internal/core/domain"
	"cuoc_thi_hoa_hau/internal/pkg/common"
	"cuoc_thi_hoa_hau/internal/pkg/validation"
	"errors"
	"fmt"
	"log"
	"time"
)

// CreateContestantProfile is the resolver for the createContestantProfile field.
func (r *mutationResolver) CreateContestantProfile(ctx context.Context, input model.CreateContestantInput) (*model.Contestant, error) {
	// 0. Validate Input First
	if err := validation.ValidateCreateContestantInput(input); err != nil {
		return nil, fmt.Errorf("validation error: %w", err)
	}

	// 1. Authentication Check
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	// 2. Map Graph Input to Domain Entity
	dob, err := time.Parse(common.DateLayoutISO, input.Dob)
	if err != nil {
		return nil, errors.New("invalid date format (YYYY-MM-DD)")
	}

	domainEntity := ToDomainContestant(input, dob)

	// 3. Call Service
	created, err := r.ContestantSvc.CreateProfile(ctx, userID, domainEntity)
	if err != nil {
		return nil, err
	}

	// 4. Return owner view (user can see their own full data)
	return mapContestantToGraphOwner(created), nil
}

// UpdateContestantProfile is the resolver for the updateContestantProfile field.
func (r *mutationResolver) UpdateContestantProfile(ctx context.Context, input model.UpdateContestantInput) (*model.Contestant, error) {
	// 0. Validate Input First
	if err := validation.ValidateUpdateContestantInput(input); err != nil {
		return nil, fmt.Errorf("validation error: %w", err)
	}

	// 1. Authentication Check
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	// 2. Map Input to Domain Entity (Partial)
	domainEntity, err := ToDomainUpdateContestant(input)
	if err != nil {
		return nil, fmt.Errorf("invalid mapping: %w", err)
	}

	// 3. Call Service (service layer must verify ownership)
	updated, err := r.ContestantSvc.UpdateProfile(ctx, userID, domainEntity)
	if err != nil {
		return nil, err
	}

	// 4. Return owner view
	return mapContestantToGraphOwner(updated), nil
}

// Helpers
// ApproveContestant is the resolver for the approveContestant field.
func (r *mutationResolver) ApproveContestant(ctx context.Context, id string, isApproved bool) (*model.Contestant, error) {
	// RBAC Check
	if err := middleware.RequirePermission(ctx, domain.PermContestantWrite); err != nil {
		return nil, err
	}
	sub := middleware.ForContext(ctx)

	updated, err := r.ContestantSvc.ApproveContestant(ctx, sub, id, isApproved)
	if err != nil {
		return nil, err
	}

	return mapContestantToGraphFull(updated), nil
}

// checkVoteRateLimit implements per-user per-contestant daily rate limiting (Atomic)
func (r *mutationResolver) checkVoteRateLimit(ctx context.Context, userID, contestantID string) error {
	// Key format: vote_limit:YYYYMMDD:userID:contestantID
	date := time.Now().Format("20060102")
	key := fmt.Sprintf("vote_limit:%s:%s:%s", date, userID, contestantID)

	// Increment atomically
	count, err := r.CacheSvc.Incr(ctx, key)
	if err != nil {
		// Log error and fail closed for security in a contest
		log.Printf("[SECURITY] Rate limit cache error: %v", err)
		return errors.New("hệ thống đang bận, vui lòng thử lại sau")
	}

	// Set expiry (24h is enough as the key contains the date)
	if count == 1 {
		_ = r.CacheSvc.Set(ctx, key, "1", 24*time.Hour)
	}

	// If count > 1, they already voted today
	if count > 1 {
		return errors.New("bạn đã bình chọn cho thí sinh này trong hôm nay rồi")
	}

	return nil
}

// VoteForContestant is the resolver for the voteForContestant field.
func (r *mutationResolver) VoteForContestant(ctx context.Context, id string) (bool, error) {
	// Authentication check
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return false, errors.New("unauthorized")
	}

	// Rate limit check (1 vote per user per contestant per day)
	if err := r.checkVoteRateLimit(ctx, userID, id); err != nil {
		return false, err
	}

	// Get Client Info
	ip, ua := middleware.GetClientInfo(ctx)

	// Call Service
	if err := r.ContestantSvc.VoteForContestant(ctx, userID, id, ip, ua); err != nil {
		return false, err
	}

	return true, nil
}

// Helper Functions

// End of Mappers (Moved to mapper.go)

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.Contestant, error) {
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	profile, err := r.ContestantSvc.GetMyProfile(ctx, userID)
	if err != nil {
		return nil, err
	}
	// User viewing their own profile - return owner view
	return mapContestantToGraphOwner(profile), nil
}

// PublicContestants is the resolver for the publicContestants field.
func (r *queryResolver) PublicContestants(ctx context.Context, page *int, limit *int) ([]*model.Contestant, error) {
	// Normalize pagination
	p, l := validation.NormalizePagination(page, limit)
	offset := int64((p - 1) * l)
	limit64 := int64(l)

	// 1. Try Cache First (if it's the first page)
	cacheKey := fmt.Sprintf("public_contestants:p%d:l%d", p, l)
	var cachedRes []*model.Contestant
	if err := r.CacheSvc.Get(ctx, cacheKey, &cachedRes); err == nil && cachedRes != nil {
		return cachedRes, nil
	}

	// 2. Cache Miss: Fetch from DB
	list, _, err := r.ContestantSvc.GetPublicList(ctx, limit64, offset)
	if err != nil {
		return nil, err
	}

	var res []*model.Contestant
	for _, c := range list {
		res = append(res, mapPublicContestantToGraph(c))
	}

	// 3. Save to Cache (Optimize: 5 minutes TTL for list)
	if err := r.CacheSvc.Set(ctx, cacheKey, res, 5*time.Minute); err != nil {
		log.Printf("[Cache] Failed to set public contestants: %v", err)
	}

	return res, nil
}

// PublicContestantDetail is the resolver for the publicContestantDetail field.
func (r *queryResolver) PublicContestantDetail(ctx context.Context, id string) (*model.Contestant, error) {
	// 1. Try Cache
	cacheKey := fmt.Sprintf("contestant_detail:%s", id)
	var cached *model.Contestant
	if err := r.CacheSvc.Get(ctx, cacheKey, &cached); err == nil && cached != nil {
		return cached, nil
	}

	// 2. Cache Miss
	c, err := r.ContestantSvc.GetPublicDetail(ctx, id)
	if err != nil {
		return nil, err
	}
	res := mapPublicContestantToGraph(c)

	// 3. Save to Cache (5 minutes)
	_ = r.CacheSvc.Set(ctx, cacheKey, res, 5*time.Minute)

	return res, nil
}

// AdminContestants is the resolver for the adminContestants field.
func (r *queryResolver) AdminContestants(ctx context.Context, page *int, limit *int, status *string) ([]*model.Contestant, error) {
	// RBAC Check
	if err := middleware.RequirePermission(ctx, domain.PermContestantWrite); err != nil {
		return nil, err
	}

	// Normalize pagination with max limit enforcement
	p, l := validation.NormalizePagination(page, limit)

	list, _, err := r.ContestantSvc.GetAdminList(ctx, int64(l), int64((p-1)*l), status)
	if err != nil {
		return nil, err
	}

	var res []*model.Contestant
	for _, c := range list {
		// Admin gets full data
		res = append(res, mapContestantToGraphFull(c))
	}
	return res, nil
}
