package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"cuoc_thi_hoa_hau/internal/adapter/graph/middleware"
	"cuoc_thi_hoa_hau/internal/adapter/graph/model"
	"cuoc_thi_hoa_hau/internal/core/domain"
	"errors"
)

// SendFeedback allows a candidate to submit a feedback.
func (r *mutationResolver) SendFeedback(ctx context.Context, input model.CreateFeedbackInput) (bool, error) {
	// 1. Auth Check: Only Candidates can complain/propose
	user, ok := ctx.Value(middleware.UserCtxKey).(*domain.AuthClaims)
	if !ok || user.Role != string(domain.RoleCandidate) {
		return false, errors.New("bạn không có quyền thực hiện hành động này")
	}

	// 2. Map Input -> Domain
	feedback := &domain.Feedback{
		Title:   input.Title,
		Content: input.Content,
		Type:    domain.FeedbackType(input.Type),
	}

	// 3. Call Service
	if err := r.FeedbackSvc.SendFeedback(ctx, user.UserID, feedback); err != nil {
		return false, err
	}

	return true, nil
}

// MyFeedbacks retrieves feedbacks submitted by the requesting user.
func (r *queryResolver) MyFeedbacks(ctx context.Context) ([]*model.Feedback, error) {
	// 1. Auth Check
	user, ok := ctx.Value(middleware.UserCtxKey).(*domain.AuthClaims)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	// 2. Standardize Pagination
	l := int64(10)
	// if limit != nil { l = int64(*limit) }
	o := int64(0)
	// if offset != nil { o = int64(*offset) }

	// 3. Call Service
	list, _, err := r.FeedbackSvc.GetMyFeedbacks(ctx, user.UserID, l, o)
	if err != nil {
		return nil, err
	}

	// 4. Map Domain -> Model
	items := make([]*model.Feedback, 0)
	for _, f := range list {
		items = append(items, &model.Feedback{
			ID: f.ID,
			// UserID:    f.UserID, // Removed as not in model
			Title:     f.Title,
			Content:   f.Content,
			Type:      string(f.Type),
			Status:    string(f.Status),
			CreatedAt: f.CreatedAt, // Time type match
		})
	}

	return items, nil
}
