package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"cuoc_thi_hoa_hau/internal/adapter/graph/model"
	"fmt"
)

// Schedules is the resolver for the schedules field.
func (r *queryResolver) Schedules(ctx context.Context, filterType *string) ([]*model.Schedule, error) {
	panic(fmt.Errorf("not implemented: Schedules - schedules"))
}

// ScheduleDetail is the resolver for the scheduleDetail field.
func (r *queryResolver) ScheduleDetail(ctx context.Context, id string) (*model.Schedule, error) {
	panic(fmt.Errorf("not implemented: ScheduleDetail - scheduleDetail"))
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) PublicSchedules(ctx context.Context, limit *int, offset *int) (*model.ScheduleList, error) {
	// Standardize input
	l := int64(10)
	if limit != nil {
		l = int64(*limit)
	}
	o := int64(0)
	if offset != nil {
		o = int64(*offset)
	}

	// Call Service
	schedules, total, err := r.ScheduleService.GetPublicSchedules(ctx, l, o)
	if err != nil {
		return nil, err
	}

	// Map Domain -> GraphQL Model
	items := make([]*model.Schedule, 0)
	for _, s := range schedules {
		items = append(items, mapToScheduleGraphModel(s))
	}

	// Return Pagination Wrapper
	return &model.ScheduleList{
		Items: items,
		Total: int(total),
	}, nil
}
func mapToScheduleGraphModel(s *domain.Schedule) *model.Schedule {
	if s == nil {
		return nil
	}
	return &model.Schedule{
		ID:          s.ID,
		Title:       s.Title,
		Description: s.Description,
		Type:        model.ScheduleType(s.Type),
		Location:    s.Location,
		StartTime:   s.StartTime.Format(time.RFC3339),
		EndTime:     s.EndTime.Format(time.RFC3339),
		CreatedAt:   s.CreatedAt.Format(time.RFC3339),
	}
}
*/
