package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"cuoc_thi_hoa_hau/internal/adapter/graph/middleware"
	"cuoc_thi_hoa_hau/internal/adapter/graph/model"
	"cuoc_thi_hoa_hau/internal/core/domain"
	"errors"
)

// SubmitScore is the resolver for the submitScore field.
func (r *mutationResolver) SubmitScore(ctx context.Context, input model.ScoreInput) (*model.Score, error) {
	// 1. Check Permission (RBAC)
	if err := middleware.RequirePermission(ctx, domain.PermScoreWrite); err != nil {
		return nil, err
	}

	// 2. Get User ID
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	// 3. Map Input
	score := ToDomainScore(input)

	// 4. Get Client Info
	ip, ua := middleware.GetClientInfo(ctx)

	// 5. Call Service
	if err := r.ScoreSvc.SubmitScore(ctx, userID, score, ip, ua); err != nil {
		return nil, err
	}

	// 5. Return
	return ToGraphScore(score), nil
}

// MyScores is the resolver for the myScores field.
func (r *queryResolver) MyScores(ctx context.Context) ([]*model.Score, error) {
	// 1. Auth Check - Using consistent retrieval from context
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized: vui lòng đăng nhập")
	}

	// 2. Call Service
	scores, err := r.ScoreSvc.GetMyScores(ctx, userID)
	if err != nil {
		return nil, err
	}

	// 3. Map Domain -> Model
	var result []*model.Score
	for _, s := range scores {
		result = append(result, ToGraphScore(s))
	}

	return result, nil
}
